package tournament

import (
	"net/http"

	"boutline/internal/types"

	"github.com/danielgtaylor/huma/v2"
)

const tournamentBasePath = "/api/v1/tournaments"

func RegisterTournamentRoutes(api huma.API, params *types.ServiceParams) {
	RegisterTournamentService(api, NewTournamentService(NewTournamentRepository(params.DB)))
}

func RegisterTournamentService(api huma.API, service TournamentService) {
	huma.Register(api, huma.Operation{
		OperationID:   "createTournament",
		Method:        http.MethodPost,
		Path:          tournamentBasePath,
		Summary:       "Create a tournament",
		Description:   "The join code is generated by the server. It cannot be chosen.",
		Tags:          []string{"Tournaments"},
		DefaultStatus: http.StatusCreated,
	}, service.CreateTournament)

	huma.Register(api, huma.Operation{
		OperationID: "listTournaments",
		Method:      http.MethodGet,
		Path:        tournamentBasePath,
		Summary:     "List tournaments",
		Tags:        []string{"Tournaments"},
	}, service.ListTournaments)

	huma.Register(api, huma.Operation{
		OperationID: "getTournamentByID",
		Method:      http.MethodGet,
		Path:        tournamentBasePath + "/{id}",
		Summary:     "Get a tournament by ID",
		Tags:        []string{"Tournaments"},
	}, service.GetTournamentByID)

	huma.Register(api, huma.Operation{
		OperationID: "getTournamentByCode",
		Method:      http.MethodGet,
		Path:        tournamentBasePath + "/code/{code}",
		Summary:     "Get a tournament by its join code",
		Description: "The code is case-insensitive.",
		Tags:        []string{"Tournaments"},
	}, service.GetTournamentByCode)

	huma.Register(api, huma.Operation{
		OperationID: "updateTournamentByID",
		Method:      http.MethodPatch,
		Path:        tournamentBasePath + "/{id}",
		Summary:     "Update a tournament",
		Description: "A tournament that has ended cannot be edited.",
		Tags:        []string{"Tournaments"},
	}, service.UpdateTournamentByID)

	huma.Register(api, huma.Operation{
		OperationID: "startTournament",
		Method:      http.MethodPost,
		Path:        tournamentBasePath + "/{id}/start",
		Summary:     "Start a tournament",
		Description: "Moves a pending tournament to active.",
		Tags:        []string{"Tournaments"},
	}, service.StartTournament)

	huma.Register(api, huma.Operation{
		OperationID: "completeTournament",
		Method:      http.MethodPost,
		Path:        tournamentBasePath + "/{id}/complete",
		Summary:     "Complete a tournament",
		Description: "Moves an active tournament to end and records completed_at. The tournament becomes immutable.",
		Tags:        []string{"Tournaments"},
	}, service.CompleteTournament)
}
